apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx

    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: ingress-server-grpc
spec:
  rules:
    - host: k8s.kkweon.dev
      http:
        paths:
          - backend:
              serviceName: hello-server
              servicePort: https
            path: /grpc/?(.*)
  tls:
    - hosts:
        - k8s.kkweon.dev
      secretName: kkweon-tls
