apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-server
  annotations:
    sidecar.istio.io/inject: "false"
  name: hello-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-server
  template:
    metadata:
      labels:
        app: hello-server
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - image: hello-server
          name: hello-server
          ports:
            - name: https
              containerPort: 7900
          command:
            - "./server"
          args:
            - "-listen-addr=0.0.0.0:7900"
            - "-ca-cert=/etc/server/ca.crt"
            - "-tls-cert=/etc/server/server.crt"
            - "-tls-key=/etc/server/server.key"

          readinessProbe:
            initialDelaySeconds: 5
            exec:
              command:
                - "/bin/grpc_health_probe"
                - "-addr=localhost:7900"
                - "-tls"
                - "-tls-ca-cert=/etc/server/ca.crt"
                - "-tls-client-cert=/etc/server/server.crt"
                - "-tls-client-key=/etc/server/server.key"

          livenessProbe:
            initialDelaySeconds: 10
            exec:
              command:
                - "/bin/grpc_health_probe"
                - "-addr=localhost:7900"
                - "-tls"
                - "-tls-ca-cert=/etc/server/ca.crt"
                - "-tls-client-cert=/etc/server/server.crt"
                - "-tls-client-key=/etc/server/server.key"
          volumeMounts:
            - name: hello-tls
              readOnly: true
              mountPath: /etc/server

      volumes:
        - name: "hello-tls"
          secret:
            secretName: "hello-tls"
