apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-server
  name: hello-server
spec:
  ports:
    - name: https
      port: 7900
      protocol: TCP
      targetPort: https
      nodePort: 30000
  selector:
    app: hello-server
  type: NodePort
