apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-server
  annotations:
    sidecar.istio.io/inject: "false"
  name: hello-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-server
  template:
    metadata:
      labels:
        app: hello-server
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - image: envoyproxy/envoy:v1.14.1
          name: envoy
          command:
            - /usr/local/bin/envoy
          args:
            - "-c /etc/envoy/envoy.yaml"
            - "-l trace"
          volumeMounts:
            - name: envoy-yaml
              readOnly: true
              mountPath: /etc/envoy/envoy.yaml
              subPath: envoy.yaml

          ports:
            - name: http
              containerPort: 8080
            - name: http-admin
              containerPort: 9901

        - image: kkweon/hello-server
          name: hello-server
          ports:
            - name: grpc
              containerPort: 7900
          command:
            - "/app/server"

          args:
            - "-listen-addr=0.0.0.0:7900"
            #- "-tls-cert=/etc/server/tls.crt"
            #- "-tls-key=/etc/server/tls.key"

          readinessProbe:
            initialDelaySeconds: 5
            exec:
              command:
                - "/bin/grpc_health_probe"
                - "-addr=0.0.0.0:7900"
                #- "-tls"
                #- "-tls-server-name=k8s.kkweon.dev"
                #- "-tls-client-cert=/etc/server/tls.crt"
                #- "-tls-client-key=/etc/server/tls.key"

          livenessProbe:
            initialDelaySeconds: 10
            exec:
              command:
                - "/bin/grpc_health_probe"
                - "-addr=0.0.0.0:7900"
                #- "-tls"
                #- "-tls-server-name=k8s.kkweon.dev"
                #- "-tls-client-cert=/etc/server/tls.crt"
                #- "-tls-client-key=/etc/server/tls.key"

          #volumeMounts:
          #- name: hello-tls
          #readOnly: true
          #mountPath: /etc/server

      volumes:
        #- name: "hello-tls"
        #secret:
        #secretName: "kkweon-tls"
        - name: envoy-yaml
          configMap:
            name: envoy-yaml
