apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-server
  name: hello-server
spec:
  ports:
    - name: grpc
      port: 7900
    - name: http
      port: 8080

  selector:
    app: hello-server
  type: ClusterIP
