apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-server
  annotations:
    sidecar.istio.io/inject: "false"
  name: hello-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-server
  template:
    metadata:
      labels:
        app: hello-server
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - image: kkweon/hello-server
          name: hello-server
          ports:
            - name: https
              containerPort: 7900
          command:
            - "/app/server"

          args:
            - "-listen-addr=0.0.0.0:7900"

          readinessProbe:
            initialDelaySeconds: 5
            exec:
              command:
                - "/bin/grpc_health_probe"
                - "-addr=localhost:7900"

          livenessProbe:
            initialDelaySeconds: 10
            exec:
              command:
                - "/bin/grpc_health_probe"
                - "-addr=localhost:7900"
          volumeMounts:
            - name: hello-tls
              readOnly: true
              mountPath: /etc/server

      volumes:
        - name: "hello-tls"
          secret:
            secretName: "hello-tls"
